os:
  - linux
  - osx

sudo: required

# install Tex Live 2015 and update to the latest packages
install:
  - curl -sSL https://github.com/nanmu42/CQUThesisSupply/raw/master/install-tl-mini.sh | sed 's!http://mirrors.ustc.edu.cn/CTAN!http://ctan.sharelatex.com/tex-archive!' | sudo bash
  - source ~/.bash_profile
  - export TLMGR=`which tlmgr`
  - sudo $TLMGR update --self --all -repository http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet/

script:
  - make doc
  - make main