sudo: required

services:
  - docker

before_install:
  - docker version
  - docker info
  - docker pull nanmu42/tex-package-test-bench
  - docker image ls
  - docker volume create --name packages

before_script:
  - ls -lsa
  
script:
  - sudo docker run -it --privileged -v packages:/miktex/.miktex -v `pwd`:/miktex/work nanmu42/tex-package-test-bench make cls
  - sudo docker run -it --privileged -v packages:/miktex/.miktex -v `pwd`:/miktex/work nanmu42/tex-package-test-bench make thesis
  - sudo docker run -it --privileged -v packages:/miktex/.miktex -v `pwd`:/miktex/work nanmu42/tex-package-test-bench make doc