os:
  - linux

sudo: required

install:
 - source ./toolkit/texlive.sh
 - make cls
 - source ./toolkit/dependencyresort.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - make doc
  - make main